language: java

jdk:
  - oraclejdk8


sudo: false

branches:
  only:
  - master
notifications:
  email:
  - blendboy@gmail.com
  - ceciliac86548@gmail.com

#Documentaci贸n de c贸mo descargar un archivo de internet para ser usado en el build: https://github.com/cucumber/cucumber-jvm/blob/master/.travis.yml
#Documentaci贸n de c贸mo incluir un JAR customizado, dentro del repositorio local de maven: http://www.mkyong.com/maven/how-to-include-library-manully-into-maven-local-repository/
before_install:
  - wget https://github.com/cecylopez/inventario/releases/download/release/inventario-1.0.0-RELEASE.jar
  - mvn install:install-file -Dfile=$PWD/inventario-1.0.0-RELEASE.jar -DgroupId=foobar -DartifactId=inventario -Dversion=1.0.0-RELEASE -Dpackaging=jar
